#!/usr/bin/env python3

import os
from Crypto.PublicKey import RSA
import subprocess

keys_path = "./keys"

# Check if terraform show returns anything
terr_show = subprocess.run(["terraform", "show"], stdout=subprocess.PIPE, text=True)

# Make the key
def key_generator(key_name):
    key = RSA.generate(2048)
    with open(f"./keys/private_key_{key_name}", "wb") as f:
        os.chmod(f"./keys/private_key_{key_name}", 0o600)
        f.write(key.exportKey("PEM"))
    pubkey = key.publickey()
    with open (f"./keys/public_key.pub_{key_name}", "wb") as f:
        f.write(pubkey.exportKey("OpenSSH"))

# Check if keys path exists, if not, create it
if os.path.exists(keys_path):
    key_generator("database")
    key_generator("application")
else:
    os.mkdir(keys_path)
    key_generator("database")
    key_generator("application")

